# Generated by Django 5.2.6 on 2026-08-26 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='référence')),
                ('nom_client', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('zone', models.CharField(choices=[('dakar', 'Dakar et banlieue'), ('thies', 'Thiès, Mbour'), ('regions', 'Autres régions')], max_length=12)),
                ('ville', models.CharField(max_length=80)),
                ('adresse', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('sous_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('frais_livraison', models.PositiveIntegerField(default=0)),
                ('remise', models.PositiveIntegerField(default=0)),
                ('code_promo', models.CharField(blank=True, max_length=32)),
                ('total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('moyen_paiement', models.CharField(choices=[('wave', 'Wave'), ('om', 'Orange Money'), ('cb', 'Carte bancaire'), ('cod', 'À la livraison')], max_length=6)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('payee', 'Payée'), ('preparation', 'En préparation'), ('expediee', 'En route'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=12)),
                ('creee_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-creee_le'],
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('commentaire', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente de modération'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='en_attente', max_length=12)),
                ('ecrit_le', models.DateTimeField(auto_now_add=True)),
                ('modere_le', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='catalogue.produit')),
                ('commande', models.ForeignKey(help_text="La commande livrée qui donne le droit d'écrire cet avis", on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='ventes.commande')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ['-ecrit_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=160)),
                ('slug_produit', models.SlugField(help_text='Pour reconstruire le lien vers la fiche', max_length=180)),
                ('url_image', models.URLField(blank=True, max_length=500)),
                ('libelle_option', models.CharField(help_text='« Rose poudré · 4 »', max_length=80)),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.commande')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='catalogue.variante')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen', models.CharField(choices=[('wave', 'Wave'), ('om', 'Orange Money'), ('cb', 'Carte bancaire'), ('cod', 'À la livraison')], max_length=6)),
                ('montant', models.PositiveIntegerField()),
                ('etat', models.CharField(choices=[('initie', 'Initié'), ('en_attente', 'En attente du prestataire'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='initie', max_length=12)),
                ('reference_prestataire', models.CharField(blank=True, db_index=True, max_length=120)),
                ('reponse_brute', models.JSONField(blank=True, default=dict)),
                ('initie_le', models.DateTimeField(auto_now_add=True)),
                ('confirme_le', models.DateTimeField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.commande')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-initie_le'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, help_text='Laisser vide pour une remise appliquée sans code', max_length=32, null=True, unique=True)),
                ('type', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant', 'Montant fixe')], default='pourcentage', max_length=12)),
                ('valeur', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_effet', models.DateField()),
                ('duree_jours', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('portee', models.CharField(choices=[('boutique', 'Toute la boutique'), ('rayon', 'Un rayon'), ('produit', 'Un produit'), ('commande', 'Sur la commande')], default='boutique', max_length=10)),
                ('condition', models.CharField(choices=[('premiere', 'Première commande'), ('montant_minimum', "À partir d'un montant")], default='premiere', max_length=16)),
                ('montant_minimum', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, help_text='Jamais affichée en boutique', verbose_name='note interne')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='catalogue.produit')),
                ('rayon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='catalogue.rayon')),
            ],
            options={
                'verbose_name': 'campagne',
                'verbose_name_plural': 'campagnes',
                'ordering': ['-date_effet'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('type', 'pourcentage'), _negated=True), ('valeur__lte', 100), _connector='OR'), name='pourcentage_au_plus_cent')],
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', '-creee_le'], name='ventes_comm_statut_752b91_idx'),
        ),
        migrations.AddConstraint(
            model_name='commande',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('moyen_paiement', 'cod'), _negated=True), ('zone', 'dakar'), _connector='OR'), name='paiement_livraison_dakar_seulement'),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.CheckConstraint(condition=models.Q(('note__lte', 5)), name='note_sur_cinq'),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(fields=('auteur', 'commande', 'produit'), name='avis_unique_par_achat'),
        ),
    ]
