# Generated by Django 5.2.6 on 2026-08-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(default='M comme Maman', max_length=120)),
                ('signature', models.CharField(default='Le monde des mamans', max_length=160)),
                ('email_contact', models.EmailField(default='bonjour@mcommaman.com', max_length=254)),
                ('telephone', models.CharField(default='+221 77 000 00 00', max_length=32)),
                ('devise', models.CharField(default='F', max_length=8)),
                ('franco_dakar', models.PositiveIntegerField(default=25000, help_text='Sur Dakar uniquement', verbose_name='livraison offerte à partir de')),
                ('frais_dakar', models.PositiveIntegerField(default=2000)),
                ('frais_thies', models.PositiveIntegerField(default=3500)),
                ('frais_regions', models.PositiveIntegerField(default=3500)),
                ('seuil_stock_bas', models.PositiveSmallIntegerField(default=6, help_text='En dessous, le produit est signalé dans le back-office', verbose_name="seuil d'alerte de stock")),
                ('accepte_commandes', models.BooleanField(default=True, help_text='Décocher pendant les congés : la boutique reste consultable', verbose_name='accepter les commandes')),
                ('affiche_bandeau_promo', models.BooleanField(default=True)),
                ('texte_bandeau_promo', models.CharField(default='Livraison offerte à Dakar dès 25 000 F — Retours gratuits sous 14 jours', max_length=200)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'réglages',
                'verbose_name_plural': 'réglages',
            },
        ),
        migrations.CreateModel(
            name='Bandeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=120)),
                ('accroche', models.CharField(blank=True, max_length=200)),
                ('texte_alternatif', models.CharField(max_length=200, verbose_name='texte alternatif')),
                ('cadrage', models.CharField(default='50% 40%', help_text="Recadrage CSS, quand le sujet n'est pas au centre", max_length=20)),
                ('etiquette', models.CharField(blank=True, help_text='« Les grands jours »', max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bandeaux', to='catalogue.media')),
                ('produit_associe', models.ForeignKey(blank=True, help_text="L'article proposé sous la photo", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandeaux', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'photo du bandeau',
                'verbose_name_plural': "bandeau d'accueil",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='EntreeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_auteur', models.CharField(max_length=120)),
                ('action', models.CharField(help_text='« a publié », « a modifié le prix de »', max_length=80)),
                ('cible', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrée du journal',
                'verbose_name_plural': 'journal',
                'ordering': ['-date'],
            },
        ),
    ]
