# Generated by Django 5.2.6 on 2026-08-26 17:42

import clientele.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse électronique')),
                ('nom', models.CharField(max_length=120, verbose_name='nom complet')),
                ('telephone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('ville', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('preparatrice', 'Préparatrice'), ('gerante', 'Gérante')], default='cliente', max_length=16)),
                ('tailles_suivies', models.JSONField(blank=True, default=list)),
                ('newsletter', models.BooleanField(default=True, verbose_name='inscrite à la lettre')),
                ('is_active', models.BooleanField(default=True, verbose_name='compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name="accès à l'admin Django")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créé le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', clientele.models.GestionnaireUtilisateur()),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_session', models.CharField(blank=True, db_index=True, max_length=64)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'panier',
                'verbose_name_plural': 'paniers',
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='« Maison », « Bureau »…', max_length=60, verbose_name='libellé')),
                ('zone', models.CharField(choices=[('dakar', 'Dakar et banlieue'), ('thies', 'Thiès, Mbour'), ('regions', 'Autres régions')], default='dakar', max_length=12)),
                ('ville', models.CharField(max_length=80)),
                ('adresse', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('par_defaut', models.BooleanField(default=False, verbose_name='adresse par défaut')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adresse',
                'verbose_name_plural': 'adresses',
                'ordering': ['-par_defaut', 'libelle'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('par_defaut', True)), fields=('cliente',), name='une_seule_adresse_par_defaut')],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'favori',
                'verbose_name_plural': 'favoris',
                'ordering': ['-ajoute_le'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'produit'), name='favori_unique')],
            },
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_panier', to='catalogue.variante')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='clientele.panier')),
            ],
            options={
                'verbose_name': 'ligne de panier',
                'verbose_name_plural': 'lignes de panier',
                'constraints': [models.UniqueConstraint(fields=('panier', 'variante'), name='ligne_panier_unique')],
            },
        ),
    ]
