# Generated by Django 5.2.6 on 2026-08-26 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coloris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('hexa', models.CharField(default='#000000', help_text='#rrggbb', max_length=7, verbose_name='pastille')),
            ],
            options={
                'verbose_name': 'coloris',
                'verbose_name_plural': 'coloris',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('nom', models.CharField(max_length=160)),
                ('largeur', models.PositiveIntegerField(blank=True, null=True)),
                ('hauteur', models.PositiveIntegerField(blank=True, null=True)),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'média',
                'verbose_name_plural': 'photothèque',
                'ordering': ['-ajoute_le'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.SmallIntegerField(help_text='Négatif pour une sortie')),
                ('motif', models.CharField(choices=[('vente', 'Vente'), ('reappro', 'Réapprovisionnement'), ('retour', 'Retour cliente'), ('ajustement', 'Ajustement manuel'), ('annulation', 'Annulation de commande')], max_length=12)),
                ('reference', models.CharField(blank=True, help_text="Référence de commande, s'il y en a une", max_length=40)),
                ('reste', models.PositiveIntegerField(verbose_name='stock après le mouvement')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'photo de produit',
                'verbose_name_plural': 'photos de produit',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, verbose_name='nom commercial')),
                ('slug', models.SlugField(help_text='Adresse en boutique : /p/<slug>', max_length=180, unique=True)),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='référence interne')),
                ('prix', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix en F CFA')),
                ('prix_barre', models.PositiveIntegerField(blank=True, null=True, verbose_name='prix barré')),
                ('description', models.TextField(blank=True)),
                ('matiere', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(choices=[('fille', 'Fille'), ('garcon', 'Garçon'), ('mixte', 'Mixte')], default='mixte', max_length=8)),
                ('age', models.CharField(choices=[('0-1', '0 à 1 an'), ('2-10', '2 à 10 ans'), ('10-15', '10 à 15 ans')], default='2-10', max_length=6, verbose_name="tranche d'âge")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('visible', models.BooleanField(default=True, verbose_name='visible en boutique')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'rayon',
                'verbose_name_plural': 'rayons',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(help_text='S, 4, 24, TU…', max_length=12, unique=True, verbose_name='taille')),
                ('repere', models.CharField(blank=True, help_text="Indication d'âge, facultative", max_length=40, verbose_name='repère')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'taille',
                'verbose_name_plural': 'tailles',
                'ordering': ['ordre', 'valeur'],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes',
                'ordering': ['produit', 'taille'],
            },
        ),
    ]
