# Generated by Django 5.2.6 on 2026-08-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoproduit',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisations', to='catalogue.media'),
        ),
        migrations.AddField(
            model_name='photoproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalogue.produit'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rayons_illustres', to='catalogue.media'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='lies',
            field=models.ManyToManyField(blank=True, to='catalogue.rayon', verbose_name='rayons liés'),
        ),
        migrations.AddField(
            model_name='produit',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.rayon'),
        ),
        migrations.AddField(
            model_name='variante',
            name='coloris',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='catalogue.coloris'),
        ),
        migrations.AddField(
            model_name='variante',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogue.produit'),
        ),
        migrations.AddField(
            model_name='variante',
            name='taille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='catalogue.taille'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='catalogue.variante'),
        ),
        migrations.AddConstraint(
            model_name='photoproduit',
            constraint=models.UniqueConstraint(fields=('produit', 'media'), name='photo_produit_unique'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['statut', 'rayon'], name='catalogue_p_statut_a161c6_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['genre', 'age'], name='catalogue_p_genre_5971f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.CheckConstraint(condition=models.Q(('prix_barre__isnull', True), ('prix_barre__gt', models.F('prix')), _connector='OR'), name='prix_barre_superieur_au_prix'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(fields=('produit', 'taille', 'coloris'), name='variante_unique'),
        ),
    ]
