# Generated by Django 5.2.6 on 2026-08-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='univers',
            field=models.CharField(choices=[('enfant', 'Enfants'), ('maman', 'Coin Maman')], default='enfant', max_length=8),
        ),
        migrations.AddField(
            model_name='rayon',
            name='univers',
            field=models.CharField(choices=[('enfant', 'Enfants'), ('maman', 'Coin Maman')], default='enfant', max_length=8),
        ),
        migrations.AlterField(
            model_name='produit',
            name='age',
            field=models.CharField(blank=True, choices=[('2-10', '2 à 10 ans'), ('11-14', '11 à 14 ans')], default='2-10', max_length=6, verbose_name="tranche d'âge"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='genre',
            field=models.CharField(blank=True, choices=[('fille', 'Fille'), ('garcon', 'Garçon'), ('mixte', 'Mixte')], default='mixte', max_length=8),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['univers', 'statut'], name='catalogue_p_univers_7f0962_idx'),
        ),
    ]
