# Generated by Django 5.2.6 on 2026-08-27 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_reprendre_ages'),
    ]

    operations = [
        migrations.AddField(
            model_name='rayon',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Vide pour une catégorie de premier niveau', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='catalogue.rayon', verbose_name='catégorie parente'),
        ),
    ]
