# Generated by Django 5.2.6 on 2026-08-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_remove_rayon_lies_remove_rayon_parent_rayon_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='fichier',
            field=models.ImageField(blank=True, upload_to='photheque/%Y/%m', verbose_name='fichier envoyé'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, max_length=500, unique=True),
        ),
    ]
