# Generated by Django 5.2.6 on 2026-08-31 10:11

from django.db import migrations, models


def reprendre_matieres(apps, schema_editor):
    Produit = apps.get_model("catalogue", "Produit")
    Matiere = apps.get_model("catalogue", "Matiere")
    for produit in Produit.objects.exclude(matiere=""):
        matiere, _ = Matiere.objects.get_or_create(nom=produit.matiere.strip())
        produit.matieres.add(matiere)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_media_fichier_alter_media_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produit',
            name='catalogue_p_genre_5971f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='catalogue_p_univers_7f0962_idx',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='age',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='univers',
        ),
        migrations.AddField(
            model_name='produit',
            name='matieres',
            field=models.ManyToManyField(blank=True, help_text='Une composition peut réunir plusieurs matières.', related_name='produits', to='catalogue.matiere'),
        ),
        migrations.RunPython(reprendre_matieres, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='produit',
            name='matiere',
        ),
    ]
